Index View
evenset/ketabdan-project pull request #40
Opened 2018-07-16 09:12 UTC by maryamyasaei

2018-07-16 23:51 UTC, maryamyasaei commented
Can you please give me feedback on this commit ??

2018-07-17 00:02 UTC, hesamd requested changes

2018-07-17 00:02 UTC, hesamd commented on ketabdan/urls.py
>  from staticpages.views import IndexView
When you import something, you should use them too otherwise, there is no point to push your code up without functionality.

2018-07-17 00:02 UTC, hesamd commented on shortstories/views.py
> +
The goal is to render shortstories stored in the DB on html, the above code is not correct. I refer you to the tutorial view section.

2018-09-06 12:22 UTC, hesamd requested changes

2018-09-06 12:22 UTC, hesamd commented on shortstories/templates/shortstories/index.html
> +            {% for ShortStory in shortstories %}
The indentation here (number of tabs) is not correct, each block should go inside the other one. Please rename `ShortStory` to `short_story` as well.

2018-09-06 12:22 UTC, hesamd commented on shortstories/templates/shortstories/index.html
> +                <p>No ShortStories availabale</p>
Here `No ShortStories availabale` (you have a typo in avail...)is going to be shown to the user, but an English reader doesn't understand `ShortStory` (the way you wrote it), so please fix it and don't forget to update your tests, otherwise, your build fails.

2018-09-06 12:22 UTC, hesamd commented on shortstories/tests.py
> +class shortstoriesDetailViewTests(TestCase):
Add two enters between these two classes

2018-09-06 12:22 UTC, hesamd commented on shortstories/templates/shortstories/index.html
> +  {% endblock %}
Add a new line after this block

2018-09-06 12:51 UTC, mahshidy commented on shortstories/templates/shortstories/index.html
> +  {% endblock %}
Is there a lint for python you can include in the project?

2018-09-06 13:13 UTC, hesamd approved these changes

2018-09-06 13:14 UTC, merged